/* eslint-disable max-len */
/* eslint-disable @typescript-eslint/naming-convention */
const english = {
  //Gasoline Services
  stationDetails: 'Station Details',
  stationName: 'Station Name',
  areaName: 'Area',
  governorateName: 'Governorate',
  locationStreet: 'Street',
  fuelTypes: 'Fuel Types',
  PrivateFuel: 'Private',
  SuperFuel: 'Super',
  SuperFuelLabel: 'Super Fuel',
  MumtazFuel: 'Mumtaz',
  JayyidFuel: 'Jayyid',
  DieselFuel: 'Diesel',
  KeroseneFuel: 'Kerosene',
  services: 'Services',
  Bank: 'ATM',
  atmlabel: 'ATM',
  Shops: 'Shops',
  RenewableStatus: 'Status',
  GasolineList: 'Fuel Stations List',
  GoToDirection: 'Get Direction',
  Available: 'Available',
  NotAvailable: 'Not Available',
  Garage: 'Garage',
  FuelType: 'Fuel Type',
  gasolineInstructions: 'Fuel Services', //To be confirmed
  petrolStationLocator: 'Fuel Stations Locator',
  cameraLocations: 'Speed Cameras Locator',
  centersLocations: 'Traffic and Inspection Centers Locator',
  Kmh: 'Km/h',
  fuelservices: 'Fuel Services',

  gasolineEnquiry: 'Fuel Enquiry',
  gasolineEnquiryMenu: 'Fuel Enquiry',
  otherservices: 'Other Services',
  relatedservices: 'Related Services',
  vehicleEnquiry: 'Vehicle Fuel Enquiry', //to be removed

  //ourapps
  ourapps: 'Our Apps',
  view: 'View',
  preview: 'Preview',
  description: 'Description',
  screenshots: 'Application Screenshots',
  ratings: 'Ratings',
  installed: 'Installed',

  //GDT Services
  history: 'Payment History',
  historyEmptyMessage: 'There are no previous payment transactions available.',
  addNewAccount: 'Add New Account', //To be revised
  edit: 'Edit',
  delete: 'Delete',
  deleteAccount: 'Delete',
  AreYouSureDeleteAccount: 'Are you sure you want to delete these details from the list?',
  ContraventionsForVeh: 'View Contraventions for',
  vehicleRegNo: 'Vehicle Number',
  vehicleRegType: 'Registration Type',
  vehYearOfMake: 'Year of Make',
  DrivingLicenseRenewal: 'Driving License Renewal',
  DrivingLicenseRenewalPaymentDetails: 'Driving License Renewal Payment Details',
  VehicleRegistrationRenewal: 'Vehicle Registration Renewal',
  VehicleRenewalPaymentDetails: 'Vehicle Registration Renewal Payment Details',
  MinorTrafficContraventions: 'Minor/GCC Traffic Contraventions',
  PaymentofTrafficContraventions: 'Payment of Traffic Contraventions',
  home: 'Home',
  aboutApp: 'About the App',
  Notifications: 'Notifications',
  Instructions: 'Instructions and FAQs',
  Help: 'Help',
  faqLabel: 'FAQs',
  PersonalNumber: 'Personal Number',
  IdCardExpiryDate: 'Identity Card Expiry Date',
  EnterIdCardExpiryDate: 'Enter Identity Card Expiry Date',
  BlockNumber: 'Block Number',
  LicenseType: 'License Type',
  LicenseCategory: 'License Category',
  ValidUntil: 'Valid Until',
  ValidUntilVRR: 'Valid Until',
  TrafficFees: 'Traffic Fees',
  TransportationFees: 'Transportation Fees',
  EnterPersonalNumber: 'Enter Personal Number',
  EnterBlockNumber: 'Enter Block Number',
  EnterVehiclesNo: 'Enter Vehicle Number',
  EnterYearOfMake: 'Enter Year of Make',
  year: 'Year of Make',
  Amount: 'Amount',
  Details: 'Details',
  TicketNumber: 'Ticket Number',
  BD: 'BD',
  DrivingLicenseDetails: 'Driving License Details',
  CourtTrafficContraventions: 'Court Contraventions',
  TotalAmountDue: 'Total Amount Due',
  TotalSelectedAmount: 'Total Selected Amount',
  Continue: 'Continue',
  DueSummary: 'Summary',
  ModelandRegistration: 'Vehicle',
  model: 'Vehicle Model',
  manufacture: 'Vehicle Make',
  Pay: 'Pay',
  RegistrationType: 'Registration Type',
  VehiclesRegistrationDetails: 'Vehicle Registration Details',
  VehiclesNo: 'Vehicle Number',
  PaymentAuthorizationCode: 'Payment Authorization Code',
  TransactionID: 'Transaction ID',
  Time: 'Time',
  Date: 'Date',
  DateandTime: 'Date & Time',
  QuickPay: 'Quick Pay',
  ContraventionsDetails: 'Contraventions Details',
  ContraventionType: 'Contravention Type',
  AllVehicles: 'All Owned Vehicles',
  QuickPayment: 'Quick Pay',
  Submit: 'Submit',
  EnterMobileNumber: 'Enter Mobile Number',
  EnterEmail: 'Enter Email',
  fbSocial: 'Get Social With Us On Facebook',
  titterSocial: 'Get Social With Us On Twitter',
  Cancel: 'Cancel',
  Yes: 'Yes',
  No: 'No',
  Email: 'Email',
  PhysicalAddress: 'Physical Address',
  PostalAddress: 'Postal Address',
  Flat: 'Flat',
  Building: 'Building',
  Block: 'Block',
  laneRoadStreet: 'Road',
  MobileForSms: 'Mobile Number',
  EnterFlat: 'Enter Flat',
  EnterBuilding: 'Enter Building',
  EnterBlock: 'Enter Block',
  EnterLaneRoadStreet: 'Enter the Road',
  POBox: 'P.O. Box Number',
  EnterPOBox: 'Enter P.O. Box Number',
  PaymentReceipt: 'Payment Receipt',
  PaymentType: 'Payment Method',
  ReceiptNo: 'Receipt Number',
  PostalTrackingNo: 'Postal Tracking Number',
  Fine: 'Fine',
  Exit: 'Exit',
  BHD: 'BD',
  NA: '-',
  Location: 'Location',
  CRNumber: 'Commercial Registration Number',
  EnterCRNumber: 'Enter Commercial Registration Number',
  CRExpireDate: 'Commercial Registration Expiry Date',
  FirstIssue: 'First Issuance',
  ExpireDate: 'Registration Expiry Date',
  dlrExpireDate: 'License Expiry Date',
  TotalAmount: 'Total Amount',
  Invalid: 'Invalid',
  CommercialRegistrationNo: 'Commercial Registration Number',
  selectManufacturer: 'Select Vehicle Make',
  selectModel: 'Select Vehicle Model',
  selectYear: 'Select Year of Make',
  Specific: 'Specific Vehicle',
  selectRegistrationType: 'Select Registration Type',
  selectLicenseType: 'Select License Type',
  selectLicenseCategory: 'Select License Category',
  numberRequired4: 'Must be 4 digits',
  numberRequired8: 'Must be 8 digits',
  numberRequired9: 'Must be 9 digits',
  numberMin3Max4: 'Should be 3-4 digits',
  numberMin3Max5: 'Should be 3-5 digits',
  numberMin1Max6: 'Should be 1-6 digits',
  numberMin7Max8: 'Should be 1-8 digits',
  idNumberMinMax: 'Should be 8-15 digits',
  Invalid_Block_No: 'Please enter a valid Block Number',
  Invalid_Email: 'Please provide a valid Email Address. Accepted email format should be similar to username@domain.com',
  Invalid_Mobile: 'Please enter a valid Mobile Number, without entering the country code (+973)',
  Invalid_Numeric: 'This field should contain numbers only',
  Invalid_Entry: 'Please complete the information required correctly',
  requiredEntry: 'Please complete the information required',
  Invalid_Building_No: 'Please enter a valid Building Number',
  Invalid_Flat_No: 'Please enter a valid Flat Number',
  Invalid_Road_No: 'Please enter a valid Road',
  Invalid_Year_of_Make: 'Please enter a valid Year of Make',
  datePattern: 'Please enter the date in this format: yyyy-MM-dd (for example: 2000-01-31)',
  minDate: 'Can not be in the past',
  timePattern: 'Please enter the time in this format: HH:mm (for example: 22:44)',
  minTime: 'Can not be in the past',
  isRenewable: 'Renewable',
  notRenewable: 'Not Renewable',
  distance: 'Distance',
  CrNo: 'Commercial Registration Number',
  allVehicles: 'All Owned Vehicles',
  vehiclesNo: 'Vehicle Number',
  receiptDetailLabel: 'Receipt Details',
  ticketdetails: 'Ticket Details',
  remarks: 'Remarks',
  insuranceStartDate: 'Insurance Start Date',
  insuranceStartTime: 'Insurance Start Time',
  insuranceEndDate: 'Insurance End Date',
  chassisNumber: 'Chassis Number',
  EnterChassisNumber: 'Enter Chassis Number',
  gdtLabel: 'eTraffic',
  faqGdtLabel: 'Traffic Services',
  ok: 'Ok',
  skipLabel: 'Skip',
  doneLabel: 'Done',
  ampersandSignLabel: '&',
  reset: 'Reset',
  showAll: 'Show All',
  inAppBrowserLoadError: 'Error loading page. Try again later',
  CRNumberShort: 'CR Number',
  EnterFullName: 'Enter first name, middle name and last name',
  version: 'Version',
  shareapp: 'Share the App',

  //CourtTrafficContraventions
  CourtCaseNumber: 'Prosecution Number',
  SpeedLimit: 'Speed Limit (km/h)',
  MapSpeedLimit: 'Speed Limit',
  SpeedRecorded: 'Speed Recorded (km/h)',

  //Vehicles Registration Details
  VehicleWeight: 'Vehicle Weight (kg)',
  InsuranceName: 'Insurance Company Name',
  Status: 'Status',

  //ekey Login
  eKeyLoginLabel: 'eKey Login',
  passwordLabel: 'Password',
  forgotPasswordLabel: 'Forgot Password',
  enterPassword: 'Enter Password',
  enterPasswordRequired: 'Please enter Password',
  newUserLabel: 'New User',
  logInLabel: 'Login',
  logoutLabel: 'Logout',
  confirmLogoutMessage: 'Are you sure you want to logout?',

  //update contact
  contactUpdateLabel: 'Update Contact Details',
  phoneNumberLabel: 'Phone Number',
  enterValidPhoneNumber: 'Please enter an 8 digit Phone Number',
  noDetailsChange: 'No changes were made',
  enterPhoneNumber: 'Enter Phone Number',
  confirmEmail: 'Confirm Email',
  enterConfirmEmail: 'Enter Confirm Email',
  mismatchedEmail: 'The provided emails do not match',
  mismatchedMobile: 'The provided Mobile Number do not match',
  confirmMobile: 'Confirm Mobile Number',

  //Dashboard-service
  MyTransactions: 'My Traffic Record',
  TotalNumberOfPoints: 'Total Number of Points',
  TotalContraventionsAmount: 'Traffic Contraventions Total Amount',
  TotalLicenseRenewalAmount: 'Driving License(s) Renewal Total Amount',
  TotalVehiclesRenewalAmount: 'Vehicle(s) Registration Renewal Total Amount',
  DrivingLicenseListDetails: 'Driving License(s) Details',
  VehiclesRegistrationListDetails: 'Vehicle(s) Registration Details',
  TrafficContraventionsAgainstVehicle: 'Traffic Contraventions (Against Vehicle)',
  TrafficContraventionsAgainstCPR: 'Traffic Contraventions (Against CPR)',
  TicketType: 'Ticket Type',
  welcomePageLabel: 'Welcome',
  Points: 'Points',
  PayableContraventions: 'Payable Contravention(s)',
  RenewableVehicle: 'Renewable Vehicle(s)',
  RenewableDrivingLicense: 'Renewable Driving License(s)',
  TrafficContraventions: 'Traffic Contraventions',
  VehicleRegistration: 'Vehicles Registration',
  DrivingLicense: 'Driving Licenses',
  Payable: 'Payable',
  Renewable: 'Renewable',
  Ticket: 'Ticket',

  RenewotherLicenses: 'Renew other Licenses',
  RenewotherVehicles: 'Renew other Vehicles',
  PayotherContraventions: 'Pay other Contraventions',
  PaymentStatus: 'Payment Status',
  OwnerDetails: 'Owner Details',
  IdentityNumber: 'Identity Number',
  searchLabel: 'Search',
  forassistance: 'for assistance',
  newLabel: 'NEW',
  updatedLabel: 'UPDATED',
  //Payment Receipt
  donotforgetlabel: 'Do Not Forget!',
  vrrreceiptmsg: 'This receipt is considered as a "Vehicle Registration Certificate". A copy of it must be available in the vehicle at all times.',
  dlrreceiptmsg: 'Use the postal tracking number to track your package through ',
  learnerreceiptmsg: 'This receipt is considered as a "Learner Driving License". You must keep a copy of it during the training period.',
  transportationfeemsg: 'Transportation Fees are applied only on Public Transportation Vehicles.',
  bahrainpostservices: 'Bahrain Post Services.',
  retry: 'Retry',
  PaymentAmount: 'Payment Amount',
  kmLabel: 'km',
  userName: 'Name',

  // KFC
  kfcTitle: 'King Fahad Causeway Insurance',
  kfcDescription: 'This service, allows Bahraini and Non-Bahraini citizens, residents and organizations to issue insurance policies for vehicles traveling through the King Fahad Causeway (KFC).',
  existingPoliciesTab: 'View Policy',
  newPoliciesTab: 'Purchase Policy',
  insurancePolicies: 'Insurance Policies',
  insurancePoliciesFor: 'Vehicle Number: ',
  showExpiredPolicies: 'View More',
  hideExpiredPolicies: 'View Fewer',
  noSavedInsurancePolicies: 'You can now purchase the Insurance Policy for King Fahad Causeway',
  noSavedVehicles: 'You have to add at least one vehicle to purchase a new insurance policy',
  noSavedDrivers: 'You have to add at least one driver to purchase a new insurance policy',
  policyNumber: 'Policy Number',
  tawuniyaNumber: 'Tawuniya Number',
  vatAccountNumber: 'VAT Account Number',
  EnterPolicyNumber: 'Enter Policy Number',
  policyStatus: 'Policy Status',
  policyStatusUPCOMING: 'Upcoming',
  policyStatusACTIVE: 'Active',
  policyStatusEXPIRED: 'Expired',
  policyStartsOn: 'Starts',
  policyEndsOn: 'Expires',
  policyEndedOn: 'Expired',
  policy1DayRemaining: 'Day',
  policyDaysRemaining: 'Days',
  policy1HourRemaining: 'Hour',
  policyHoursRemaining: 'Hours',
  deletePolicy: 'Delete Policy',
  AreYouSureDeletePolicy: 'Are you sure you want to delete this policy from the list?',
  vehicles: 'Vehicles',
  drivers: 'Drivers',
  viewExistingPolicy: 'View Insurance Policy',
  purchaseInsurancePolicyTitle: 'Purchase New Insurance Policy',
  addNewVehicle: 'Add Vehicle',
  addNewDriver: 'Add Driver',
  vehicleDetails: 'Vehicle Details',
  driverDetails: 'Driver Details',
  vehicleNationality: 'Vehicle Nationality',
  bahrain: 'Bahrain',
  vehicleNumber: 'Vehicle Number',
  ownerIdNumber: 'Owner Identity Number',
  ownerPersonalNumber: 'Owner Personal Number',
  EnterOwnerIdNumber: 'Enter Owner Identity Number',
  ownerBlockNumber: 'Owner Block Number',
  classOfUse: 'Class of Use',
  ownerName: 'Owner Full Name',
  ownerName2: 'Owner Name',
  EnterOwnerName: 'Enter Owner Full Name',
  leavingMake: 'Make',
  leavingModel: 'Model',
  enteringMakeModel: 'Make/Model',
  SelectEnteringMakeModel: 'Select Make/Model',
  vehicleType: 'Vehicle Type',
  color: 'Color',
  SelectColor: 'Select Color',
  saveVehicleDetails: 'Save Vehicle Details',
  duplicateVehicle: 'This vehicle already exists',
  editEkeyVehicle: 'Editing eKey vehicles is not allowed',
  driverIdNumber: 'Identity Number',
  EnterDriverIdNumber: 'Enter Identity Number',
  driver: 'Driver',
  driverName: 'Driver Name',
  driverFullName: 'Full Name',
  EnterDriverFullName: 'Enter Full Name',
  driverNationality: 'Nationality',
  driverMobileNumber: 'Mobile Number',
  EnterDriverMobileNumber: 'Enter Mobile Number',
  driverEmail: 'Email',
  EnterDriverEmail: 'Enter Email',
  driverConfirmEmail: 'Confirm Email',
  EnterDriverConfirmEmail: 'Enter Confirm Email',
  driverConfirmEmailMismatch: 'Apologies, the provided emails do not match. Please ensure that your information is valid',
  duplicateDriver: 'This driver already exists',
  saveDriverDetails: 'Save Driver Details',
  deleteVehicle: 'Delete Vehicle',
  AreYouSureDeleteVehicle: 'Are you sure you want to delete this vehicle from the list?',
  deleteDriver: 'Delete Driver',
  AreYouSureDeleteDriver: 'Are you sure you want to delete this driver from the list?',
  selectVehicle: 'Select Vehicle Number',
  selectDriver: 'Select Driver Name',
  selectDuration: 'Select Insurance Duration',
  insuranceEndDateTime: 'Insurance End Date & Time',
  roadAssistance: 'Road Assistance',
  totalAmountDue: 'Total Amount Due',
  ownerType: 'Owner Type',
  engineNumber: 'Engine Number',
  EnterEngineNumber: 'Enter Engine Number',
  vehicleNumberofSeats: 'Number of Seats in Vehicle',
  insuranceDetails: 'Insurance Details',
  insuranceStartDateTime: 'Insurance Start Date & Time',
  insuranceDuration: 'Insurance Duration',
  feesDetails: 'Fees Details (BD)',
  insurancePolicyAmount: 'Insurance Policy Amount',
  roadAssistanceAmount: 'Road Assistance Amount',
  vatAmount: 'VAT Amount',
  totalAmount: 'Total Amount',
  renew: 'Renew/Extend',
  new: 'New',
  extend: 'Extend',
  acceptUICTerms: 'I accept the terms and conditions of United Insurance Company.',
  termsAndConditions: 'Terms and Conditions',
  agree: 'I Agree',
  kfcRenewMessage: 'Please note that by extending the active or upcoming policy, a new policy will be issued starting immediately from the end date and time of the active or upcoming policy.',
  importantNote: 'Important Note',
  kfcLeavingMessage: 'When leaving Bahrain through the causeway, the insurance policy should be valid for at least 12 hours.',
  kfcEnteringMessage: 'When entering Bahrain through the causeway, the insurance policy should be valid for at least 3 days.',
  kfcBahrainVehicle: 'This policy covers Saudi Only.',
  kfcSaudiVehicle: 'This policy covers Bahrain only.',

  //Discount Vehicle Registration Renewal Fees
  vehicleRegistrationRenewalDiscount: 'Discount of Vehicle Registration Renewal Fees',
  quickServices: 'Quick Services',
  applyDiscountForVehicle: 'Apply the discount on this vehicle',
  declareDiscountMessage: 'I declare that I want to apply the 50% discount for the mentioned vehicle.*',
  vehicleRegistrationRenewalDiscountMessage: 'Kindly note that this service is provided for Bahraini vehicle owners of 60 years-of-age or above.',

  //Reserved Plates
  ReservedPlates: 'Plate Numbers',
  plateNumber: 'Plate Number',
  plateType: 'Plate Type',
  plateExpiryDate: 'Plate Expiry Date',
  reservedPlatesReceipt: 'Plate Numbers Payment Details',

  //Settings
  Setting: 'Settings',
  SelectLanguage: 'Language',
  English: 'English',
  Arabic: 'Arabic',
  enableNotification: 'Enable Notification',
  On: 'On',
  Off: 'Off',

  //common
  update: 'UPDATE',
  dismiss: 'DISMISS',
  skip: 'SKIP',

  //Webservice error
  errormsg: 'We apologize for any inconvenience caused, but unfortunately the system is currently not available. Please try again later',
  sessionerror: 'Your login session has expired. Please re-login to continue using the application',
  locationError: 'Please enable the Location Services for this application',
  bugText3: 'You don\'t have an active internet connection. Please activate it and try again',

  appratetitle: 'Rate eTraffic App',
  appratemessage: 'Please help us improve our services by rating the App',
  appratecancelbuttonlabel: 'No, Thanks',
  appratelaterbuttonlabel: 'Remind Me Later',
  apprateratebuttonlabel: 'Rate It Now',

  //ReportContraventions
  ReportContraventions: 'Report Traffic Contraventions',
  VehicleColor: 'Vehicle Color',
  SelectVehicleColor: 'Select Vehicle Color',
  PlateColor: 'Plate Color',
  SelectPlateColor: 'Select Plate Color',
  PlateCountry: 'Plate Country',
  SelectPlateCountry: 'Select Plate Country',
  PlateNumber: 'Plate Number',
  EnterPlateCountry: 'Enter Plate Number',
  ContraventionItem: 'Contravention Type',
  SelectContraventionItem: 'Select Contravention Type',
  SelectGovernorate: 'Select Governorate',
  SelectArea: 'Select Area',
  Location: 'Location',
  EnterLocation: 'Enter Location',
  LocationDesc: 'Location Description',
  EnterLocationDesc: 'Additional Directions for the Location',
  Remark: 'Remarks',
  EnterRemark: 'Enter Remarks',
  TakePhoto: 'Take Photo',
  PhotoSizeError: 'Attachment size should not exceed 2 MB',
  PhotoFormatError: 'Incorrect File format',
  MinimumPhotos: 'Please capture 2 photos of the vehicle.',
  ContraventionPhotos: 'Contravention Photos',
  Photo: 'Photo',
  AgreeDeclaration: 'Agree',
  CurrentLocation: 'Current Location',
  Declaration: 'I hereby declare that all the information provided are correct, and I acknowledge that I bear full legal responsibility if is proved otherwise. Also, I confirm my presence if I got contacted by the Public Prosecution in case the contravention was objected by the driver.',
  MoreDetails: 'Additional Details (Optional)',
  LessDetails: 'Additional Details (Optional)',

  PaymentID: 'Payment ID',
  reportingText1: 'Contraventions related to parking violations can be reported.',
  reportingText2: 'Recent photos of the committed contravention must be submitted highlighting the vehicle number and not by uploading old photos.',
  reportingText3: 'The photo cannot be taken while the offender is in his vehicle.',
  reportingText4: 'The application cannot be used while being in the driver\'s seat.',

  Address: 'Address',
  WorkingHours: 'Working Hours',
  ContactDetails: 'Contact Details',

  //Traffic Accidents Services
  TrafficAccidentsServices: 'Traffic Accidents Services',
  ComingSoon: 'Coming Soon',
  reportTrafficAccident: 'Report Traffic Accidents',
  trafficAccidentAcknowledgment: 'Traffic Accident Acknowledgment',
  viewAccidentReport: 'View Reported Traffic Accidents',
  viewInsuranceCompanies: 'Insurance Companies Locator',
  callAccidentReport: 'Call 199',
  AccidentDriverTittle: 'Please specify which driver is reporting the traffic accident:',
  affectedByTheAccident: 'Driver affected by the traffic accident',
  causedTheAccident: 'Driver who caused the traffic accident',
  TA_Q1_TEXT: 'Traffic Accidents can be reported only when there is an agreement between all parties and no injuries.',
  TA_Q2_TEXT: 'Are there any injuries resulted from the traffic accident?',
  individual: 'Driver',
  property: 'Property',
  PropertyType: 'Property Type',
  PropertyOwnerName: 'Owner Name',
  PropertyOwnerShipType: 'Ownership Type',
  PropertyAddress: 'Property Address',
  AccidentDetails: 'Accident Details',
  AccidentAddress: 'Accident Address',
  AccidentLocation: 'Accident Location',
  AccidentLocationCoordinates: 'Accident Location Coordinates',
  TrafficAccidentLocation: 'Traffic Accident Location',
  AccidentDate: 'Accident Date',
  AccidentTime: 'Accident Time',
  AccidentPhotos: 'Accident Photos',
  AccidentSubmitNote: '* I hereby declare that all information provided above are correct and I acknowledge that I bear full responsibility if it is proved otherwise.',
  AccidentSubmitNoteReporter: '* I here by declare my fault in causing the traffic accident between the vehicle I was driving (details in the Online Report) and the other vehicle(s)/properties. I also authorize the insurance companies to discharge the terms of the insurance polices and hereby declare that all the information provided are correct and valid. Furthermore, I have no objection for the insurance companies to access my details registered in General Directorate of Traffic for the purpose of issuing the accident traffic report.',
  ReporterDetails: 'Accident reporter details',
  DriverCaused: 'Driver who caused the traffic accident',
  IdentityType: 'Identity Type',
  SelectNationality: 'Select Nationality',
  DriverIdIssueDate: 'Identity Issue Date',
  DriverDetails: 'Driver Details',
  VehicleDetails: 'Vehicle Details',
  SelectInsurance: 'Select Insurance Company Name',
  InsurancePolicyNumber: 'Insurance Policy Number',
  InsuranceCompanyDetails: 'Insurance Company Details',
  Name: 'Name',
  BranchDetails: 'Branch Details',
  IndividualsTitle: 'Drivers affected by the traffic accident',
  PropertyTitle: 'Properties affected by the traffic accident',
  PropertyType: 'Property Type',
  PropertyName: 'Property Name',
  SelectPropertyType: 'Select Property Type',
  SelectPropertyOwner: 'Select Property Owner',
  SelectPropertyOwnerShipType: 'Select Property Ownership Type',
  DeleteVehicle: 'Delete Property',
  AreYouSureDeleteProperty: 'Are you sure you want to delete this property from the list?',
  ReportNumber: 'Report Number',
  EnterReportNumber: 'Enter Report Number',
  LoginbyeKeyAccount: 'Login by eKey Account',
  Owner: 'Vehicle Owner',
  Driver: 'Driver',
  InvolvedVehicle: 'Vehicle Details',
  InvolvedProperty: 'Property Details',
  ReportDetails: 'Report Details',
  ReportSubmitNote: 'I here by declare my fault in causing the traffic accident between the vehicle I was driving (details in the Online Report) and the other vehicle(s)/properties. I also authorize the insurance companies to discharge the terms of the insurance polices and hereby declare that all the information provided are correct and valid. Furthermore, I have no objection for the insurance companies to access my details registered in General Directorate of Traffic for the purpose of issuing the accident traffic report.',
  Gender: 'Gender',
  SelectGenderType: 'Select Gender',
  Male: 'MALE',
  Female: 'FEMALE',
  ResponsibleType: 'Type',
  CausedTheTrafficAccident: 'Caused the traffic accident',
  AffectedByTheTrafficAccident: 'Affected by the traffic accident',
  ReporterUserDetail: '* This driver will be considered as the reporter of the traffic accident.',
  AffectedVehicleRequired: 'Please add at least one driver affected by the traffic accident.',
  eKeyReporterRequired: 'Please add the eKey logged in user to the list of of drivers affected by the traffic accident.',
  EnterValidMobileNumber: 'Please enter a valid Mobile Number',

  VehicleAuthorization: 'Vehicle Authorization for King Fahad Causeway',
  IssuanceVehicleAuthorization: 'Issuance of Vehicle Authorization',
  ManageVehicleAuthorizations: 'Manage Issued Vehicle Authorizations',
  AuthorizationValidityVerification: 'Authorization Validity Verification',
  DriverIdentityType: 'Driver Identity Type',
  SelectDriverIdentityType: 'Select Driver Identity Type',
  DriverIdentityNumber: 'Driver Identity Number',
  AuthorizationStartDate: 'Authorization Start Date',
  AuthorizationEndDate: 'Authorization End Date',
  AuthorizationMaxStartDate: 'The Authorization Start Date must not exceed ',
  AuthorizationMaxDate: 'The Authorization End Date must not exceed ',
  AuthorizationEndDateError: 'The Authorization End Date must not be prior to the Authorization Start Date.',
  CountriesIncludedAuthorization: 'Countries Included in the Authorization',
  OwnerMobileNumber: 'Owner Mobile Number',
  OwnerEmail: 'Owner Email',
  DriverMobileNumber: 'Driver Mobile Number',
  DriverEmail: 'Driver Email',
  AuthorizationDetails: 'Authorization Details',
  Declare: 'I declare that all information entered is true and correct, and I acknowledge that I bear full responsibility for this action. *',
  AuthorizationCertificate: 'Authorization Certificate',
  AuthorizationNumber: 'Authorization Number',
  Authorization: 'Authorization',
  EnterAuthorizationNumber: 'Enter Authorization Number',
  StartDate: 'Start Date',
  EndDate: 'End Date',
  ViewCertificate: 'View Certificate',
  IssuedAuthorizationCertificateDetails: 'Issued Authorization Details',
  VehicleAuthorizationCertificateDetails: 'Vehicle Authorization Certificate Details',
  AuthorizationCertificateNote: 'Please print the authorization certificate to be used in emergency cases. In case the authorization will be used outside the GCC countries, please visit the General Directorate of Traffic (GDT) to stamp the certificate.',
  CancelAuthorization: 'Are you sure you want to cancel the authorization ?',
  Or: '-- OR --',
  ScanQr: 'Scan',
  QRError: 'Invalid QR code'
};

const arabic = {
  //Gasoline Services
  stationDetails: 'بيانات المحطة', //Newly added
  stationName: 'اسم المحطة',
  areaName: 'المنطقة',
  governorateName: 'المحافظة',
  locationStreet: 'الشارع',
  fuelTypes: 'أنواع الوقود', //Newly added
  PrivateFuel: 'الخاص',
  SuperFuel: 'السوبر',
  SuperFuelLabel: 'الوقود السوبر',
  MumtazFuel: 'الممتاز',
  JayyidFuel: 'الجيد',
  DieselFuel: 'الديزل',
  KeroseneFuel: 'الكيروسين',
  services: 'الخدمات',
  Bank: 'الصراف الآلي',
  Shops: 'محلات تجارية',
  RenewableStatus: 'الحالة',
  GasolineList: 'قائمة محطات الوقود',
  GoToDirection: 'الحصول على الاتجاه',
  addNewAccount: 'إضافة حساب جديد',
  Available: 'متاح',
  NotAvailable: 'غير متاح',
  Garage: 'ورشة تصليح',
  FuelType: 'نوع الوقود',
  distance: 'المسافة',
  gasolineInstructions: 'خدمات الوقود',

  //ourapps
  ourapps: 'تطبيقاتنا',
  view: 'عرض',
  preview: 'معاينة',
  description: 'الوصف',
  screenshots: 'صور لواجهة التطبيق',
  ratings: 'تقييم',
  installed: 'مثبت',

  //GDT Services
  history: 'المدفوعات السابقة',
  historyEmptyMessage: 'لا توجد معاملات دفع سابقة.',
  edit: 'تعديل',
  delete: 'حذف',
  deleteAccount: 'حذف',
  AreYouSureDeleteAccount: 'هل أنت متأكد من رغبتك في حذف هذه البيانات من القائمة؟',
  vehicleRegNo: 'رقم المركبة',
  vehicleRegType: 'نوع التسجيل',
  vehYearOfMake: 'سنة الصنع',
  ContraventionsForVeh: 'عرض المخالفات لـ',
  DrivingLicenseRenewal: 'تجديد رخصة السياقة',
  DrivingLicenseRenewalPaymentDetails: 'تفاصيل الدفع لتجديد رخصة السياقة',
  VehicleRegistrationRenewal: 'تجديد تسجيل المركبة',
  VehicleRenewalPaymentDetails: 'تفاصيل الدفع لتجديد تسجيل المركبة',
  MinorTrafficContraventions: 'المخالفات المرورية البسيطة/الخليجية',
  PaymentofTrafficContraventions: 'دفع المخالفات المرورية',
  home: 'الرئيسية',
  aboutApp: 'عن التطبيق',
  Notifications: 'الإشعارات',
  Instructions: 'التعليمات والأسئلة الشائعة',
  Help: 'مساعدة',
  faqLabel: 'الأسئلة الأكثر شيوعاً',
  PersonalNumber: 'الرقم الشخصي',
  IdCardExpiryDate: 'تاريخ انتهاء بطاقة الهوية',
  EnterIdCardExpiryDate: 'أدخل تاريخ انتهاء بطاقة الهوية',
  BlockNumber: 'رقم المجمع',
  LicenseType: 'نوع الرخصة',
  LicenseCategory: 'تصنيف الرخصة',
  ValidUntil: 'صالحة لغاية',
  ValidUntilVRR: 'صالح لغاية',
  TrafficFees: 'رسوم المرور',
  TransportationFees: 'رسوم المواصلات',
  EnterPersonalNumber: 'أدخل الرقم الشخصي',
  EnterBlockNumber: 'أدخل رقم المجمع',
  EnterVehiclesNo: 'أدخل رقم المركبة',
  EnterYearOfMake: 'أدخل سنة الصنع',
  year: 'سنة الصنع',
  Amount: 'المبلغ',
  Details: 'التفاصيل',
  TicketNumber: 'رقم المخالفة',
  BD: 'د.ب',
  DrivingLicenseDetails: 'تفاصيل رخصة السياقة',
  CourtTrafficContraventions: 'المخالفات المحولة للمحاكم',
  TotalAmountDue: ' مجموع المبلغ المستحق',
  TotalSelectedAmount: 'مجموع المبلغ المختار',
  Continue: 'مواصلة',
  DueSummary: 'الملخص',
  ModelandRegistration: 'المركبة',
  model: 'طراز المركبة',
  manufacture: 'صنع المركبة',
  Pay: 'دفع',
  RegistrationType: 'نوع التسجيل',
  VehiclesRegistrationDetails: 'تفاصيل تسجيل المركبات',
  VehiclesNo: 'رقم المركبة',
  PaymentAuthorizationCode: 'رمز تفويض الدفع',
  TransactionID: 'رقم معاملة الدفع',
  Time: 'الوقت',
  Date: 'التاريخ',
  DateandTime: 'التاريخ والوقت',
  Setting: 'الإعدادات',
  SelectLanguage: 'اللغة',
  English: 'English',
  Arabic: 'العربية',
  On: 'تفعيل',
  Off: 'إغلاق',
  QuickPay: 'الدفع السريع',
  ContraventionsDetails: 'تفاصيل المخالفات',
  ContraventionType: 'نوع المخالفة',
  AllVehicles: 'جميع المركبات المملوكة',
  QuickPayment: 'الدفع السريع',
  fbSocial: 'كن اجتماعيا معنا على الفيسبوك',
  titterSocial: 'كن اجتماعيا معنا على تويتر',
  Submit: 'إرسال',
  EnterMobileNumber: 'أدخل رقم الهاتف النقال',
  EnterEmail: 'أدخل البريد الإلكتروني',
  Cancel: 'إلغاء',
  Yes: 'نعم',
  No: 'لا',
  Email: 'البريد الإلكتروني',
  PhysicalAddress: 'العنوان الفعلي',
  PostalAddress: 'العنوان البريدي',
  Flat: 'شقة',
  Building: 'مبنى',
  Block: 'مجمع',
  laneRoadStreet: 'طريق',
  MobileForSms: 'رقم الهاتف النقال',
  EnterFlat: 'أدخل رقم الشقة',
  EnterBuilding: 'أدخل رقم المبنى',
  EnterBlock: 'أدخل رقم المجمع',
  EnterLaneRoadStreet: 'أدخل بيانات الطريق',
  POBox: 'رقم صندوق البريد',
  EnterPOBox: 'أدخل رقم صندوق البريد',
  PaymentReceipt: 'رصيد الدفع',
  PaymentType: 'طريقة الدفع',
  ReceiptNo: 'رقم الرصيد',
  PostalTrackingNo: 'رقم البعيثة',
  Fine: 'غرامة',
  Exit: 'خروج',
  BHD: 'د.ب',
  NA: '-',
  Location: 'المكان',
  CRNumber: 'رقم السجل التجاري',
  EnterCRNumber: 'أدخل رقم السجل التجاري',
  CRExpireDate: 'تاريخ انتهاء السجل التجاري',
  FirstIssue: 'الإصدار الأول',
  ExpireDate: 'تاريخ انتهاء التسجيل',
  dlrExpireDate: 'تاريخ انتهاء الرخصة',
  TotalAmount: 'المبلغ الكلي',
  Invalid: 'غير صالح',
  CommercialRegistrationNo: 'رقم السجل التجاري',
  petrolStationLocator: 'مواقع محطات الوقود',
  cameraLocations: 'مواقع كاميرات السرعة',
  centersLocations: 'مواقع المراكز المرورية والفحص الفني',
  Kmh: 'كم/ساعة',
  fuelservices: 'خدمات الوقود',

  gasolineEnquiry: 'الاستعلام عن الوقود',
  gasolineEnquiryMenu: 'الاستعلام عن الوقود',
  otherservices: 'خدمات أخرى',
  relatedservices: 'خدمات ذات صلة',
  vehicleEnquiry: 'الاستعلام عن الوقود', //to be removed
  selectManufacturer: 'اختر صنع المركبة',
  selectModel: 'اختر طراز المركبة',
  selectYear: 'اختر سنة الصنع',
  Specific: 'مركبة محددة',
  selectRegistrationType: 'اختر نوع التسجيل',
  selectLicenseType: 'اختر نوع الرخصة',
  selectLicenseCategory: 'اختر تصنيف الرخصة',
  numberRequired4: 'يجب أن يكون 4 أرقام',
  numberRequired8: 'يجب أن يكون 8 أرقام',
  numberRequired9: 'يجب أن يكون 9 أرقام',
  numberMin3Max4: 'يجب أن يكون من 3-4 أرقام',
  numberMin3Max5: 'يجب أن يكون من 3-5 أرقام',
  numberMin1Max6: 'يجب أن يكون من 1-6 أرقام',
  numberMin7Max8: 'يجب أن يكون من 1-8 أرقام',
  idNumberMinMax: 'يجب أن يكون من 8-15 أرقام',
  Invalid_Block_No: 'الرجاء إدخال رقم المجمع الصحيح',
  Invalid_Email: 'البريد الإلكتروني المدخل غير صحيح، يجب أن يكون بصيغة مشابهة لـ username@domain.com',
  Invalid_Mobile: 'الرجاء إدخال رقم الهاتف النقال من غير رمز الاتصال الدولي (973+)',
  Invalid_Numeric: 'يجب أن تحتوي هذه الخانة على أرقام فقط',
  Invalid_Entry: 'الرجاء استكمال البيانات بطريقة صحيحة',
  requiredEntry: 'الرجاء استكمال البيانات المطلوبة',
  Invalid_Building_No: 'الرجاء إدخال رقم المبنى الصحيح.',
  Invalid_Flat_No: 'الرجاء إدخال رقم الشقة الصحيح.',
  datePattern: 'الرجاء إدخال التاريخ بهذه الهيئة: yyyy-MM-dd (مثلاً: \u202A2000-01-31\u202C)',
  minDate: 'لا يمكن أن يكون في الماضي',
  timePattern: 'الرجاء إدخال الوقت بهذه الهيئة: HH:mm (مثلاً: 22:44)',
  minTime: 'لا يمكن أن يكون في الماضي',

  Invalid_Building_No: 'الرجاء إدخال رقم المبنى الصحيح',
  Invalid_Flat_No: 'الرجاء إدخال رقم الشقة الصحيح',
  Invalid_Road_No: 'الرجاء إدخال بيانات الطريق بشكل صحيح',
  Invalid_Year_of_Make: 'الرجاء إدخال سنة الصنع بشكل صحيح',
  isRenewable: 'قابل للتجديد',
  notRenewable: 'غير قابل للتجديد',
  CrNo: 'رقم السجل التجاري',
  allVehicles: 'جميع المركبات المملوكة',
  vehiclesNo: 'رقم المركبة',
  receiptDetailLabel: 'تفاصيل الرصيد',
  ticketdetails: 'بيانات المخالفة',
  remarks: 'ملاحظات',
  insuranceStartDate: 'تاريخ بدء التأمين',
  insuranceStartTime: 'وقت بدء التأمين',
  insuranceEndDate: 'تاريخ انتهاء التأمين',
  chassisNumber: 'رقم القاعدة',
  EnterChassisNumber: 'أدخل رقم القاعدة',
  atmlabel: 'الصراف الآلي',
  gdtLabel: 'خدمات المرور',
  faqGdtLabel: 'خدمات المرور',
  ok: 'موافق',
  skipLabel: 'تخطي',
  doneLabel: 'تم',
  ampersandSignLabel: 'و',
  enableNotification: 'تفعيل الإشعارات',
  reset: 'مسح',
  showAll: 'إظهار الكل',
  inAppBrowserLoadError: 'حدث خطأ في تحميل الصفحة. يرجى المحاولة لاحقاً',
  CRNumberShort: 'رقم السجل التجاري',
  EnterFullName: 'أدخل الاسم الأول والاسم الأوسط والاسم الأخير',
  version: 'نسخة',
  shareapp: 'انشر التطبيق',

  //CourtTrafficContraventions
  CourtCaseNumber: 'رقم النيابة',
  SpeedLimit: 'السرعة القانونية (كم/ساعة)',
  MapSpeedLimit: 'السرعة القانونية',

  SpeedRecorded: 'السرعة المسجلة (كم/ساعة)',
  Status: 'الحالة',

  //Vehicles Registration Details
  VehicleWeight: 'وزن المركبة (كغ)',
  InsuranceName: 'اسم شركة التأمين',

  //ekey Login
  eKeyLoginLabel: 'دخول المفتاح الإلكتروني',
  passwordLabel: 'كلمة المرور',
  forgotPasswordLabel: 'نسيت كلمة المرور',
  enterPassword: 'أدخل كلمة المرور',
  enterPasswordRequired: 'الرجاء إدخال كلمة المرور',
  newUserLabel: 'مستخدم جديد',
  logInLabel: 'دخول',
  logoutLabel: 'تسجيل الخروج',
  confirmLogoutMessage: 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',

  //update contact
  contactUpdateLabel: 'تحديث بيانات الاتصال',
  phoneNumberLabel: 'رقم الهاتف',
  enterValidPhoneNumber: 'الرجاء إدخال رقم هاتف مكون من 8 أرقام',
  noDetailsChange: 'لم تقم بإدخال أية تغييرات',
  enterPhoneNumber: 'أدخل رقم الهاتف',
  confirmEmail: 'تأكيد البريد الإلكتروني',
  enterConfirmEmail: 'أدخل تأكيد البريد الإلكتروني',
  mismatchedEmail: 'البريد الإلكتروني المدخل لا يتطابق',
  mismatchedMobile: 'رقم الهاتف النقال المدخل لا يتطابق',
  confirmMobile: 'تأكيد رقم الهاتف النقال',

  //Dashboard-service
  MyTransactions: 'سجلّي المروري',
  TotalNumberOfPoints: 'إجمالي عدد النقاط',
  TotalContraventionsAmount: 'مجموع مبلغ المخالفات',
  TotalLicenseRenewalAmount: ' المبلغ الكلي لتجديد رخص السياقة',
  TotalVehiclesRenewalAmount: ' المبلغ الكلي لتجديد تسجيل المركبات',
  DrivingLicenseListDetails: ' تفاصيل رخص السياقة',
  VehiclesRegistrationListDetails: 'تفاصيل تسجيل المركبات',
  TrafficContraventionsAgainstVehicle: 'المخالفات المرورية (مرتبطة بالمركبة)',
  TrafficContraventionsAgainstCPR: 'المخالفات المرورية (مرتبطة بالرقم الشخصي)',
  TicketType: 'نوع المخالفة',
  welcomePageLabel: 'مرحباً بك',
  Points: 'النقاط',
  PayableContraventions: 'المخالفات ',
  RenewableVehicle: 'المركبات القابلة للتجديد',
  RenewableDrivingLicense: 'رخص السياقة القابلة للتجديد',
  TrafficContraventions: 'المخالفات المرورية',
  VehicleRegistration: 'تسجيل المركبات',
  DrivingLicense: 'رخص السياقة',
  Payable: 'المستحق للدفع',
  Renewable: 'قابل للتجديد',
  Ticket: 'المخالفة',

  RenewotherLicenses: 'تجديد رخص أخرى',
  RenewotherVehicles: 'تجديد مركبات أخرى',
  PayotherContraventions: 'دفع مخالفات أخرى',
  PaymentStatus: 'حالة الدفع',
  OwnerDetails: 'تفاصيل المالك',
  IdentityNumber: 'رقم الهوية',
  searchLabel: 'بحث',
  forassistance: 'للمساعدة',

  donotforgetlabel: 'لا تنسى!',
  vrrreceiptmsg: 'يعتبر هذا الرصيد بمثابة "شهادة تسجيل المركبة". الرجاء الاحتفاظ بنسخة منه في المركبة في جميع الأوقات.',
  dlrreceiptmsg: ' استخدم رقم البعيثة للاستعلام عن حالة البعيثة عبر',
  learnerreceiptmsg: 'يعتبر هذا الرصيد بمثابة "رخصة تعلم سياقة". يجب الاحتفاظ بنسخة منه طوال فترة التدريب.',
  transportationfeemsg: ' تنطبق رسوم المواصلات فقط على مركبات النقل العام.',
  bahrainpostservices: ' خدمات بريد البحرين.',
  retry: 'إعادة المحاولة',
  PaymentAmount: 'المبلغ المدفوع',
  kmLabel: 'كم',
  userName: 'الاسم',
  newLabel: 'جديد',
  updatedLabel: 'محدثة',
  //common
  update: 'تحديث',
  dismiss: 'إلغاء',
  skip: 'تخطي',

  // KFC
  kfcTitle: 'التأمين لجسر الملك فهد',
  kfcDescription: 'تتيح هذه الخدمة للمواطنين، والمقيمين، والمؤسسات البحرينية وغير البحرينية إمكانية إصدار وثائق التأمين للمركبات المسافرة عبر جسر الملك فهد.',
  existingPoliciesTab: 'عرض وثيقة',
  newPoliciesTab: 'شراء وثيقة',
  insurancePolicies: 'وثائق التأمين',
  insurancePoliciesFor: 'رقم المركبة: ',
  showExpiredPolicies: 'عرض المزيد',
  hideExpiredPolicies: 'عرض أقل',
  noSavedInsurancePolicies: 'يمكنك الآن إصدار وثيقة التأمين لجسر الملك فهد',
  noSavedVehicles: 'بجب إضافة مركبة واحدة على الأقل لشراء وثيقة تأمين جديدة',
  noSavedDrivers: 'بجب إضافة سائق واحد على الأقل لشراء وثيقة تأمين جديدة',
  policyNumber: 'رقم الوثيقة',
  tawuniyaNumber: 'رقم التعاونية',
  vatAccountNumber: 'رقم حساب ضريبة القيمة المضافة',
  EnterPolicyNumber: 'أدخل رقم الوثيقة',
  policyStatus: 'حالة الوثيقة',
  policyStatusUPCOMING: 'قادمة',
  policyStatusACTIVE: 'سارية',
  policyStatusEXPIRED: 'منتهية',
  policyStartsOn: 'تبدأ',
  policyEndsOn: 'تنتهي',
  policyEndedOn: 'انتهت',
  policy1DayRemaining: 'يوم',
  policyDaysRemaining: 'يوم',
  policy1HourRemaining: 'ساعة',
  policyHoursRemaining: 'ساعة',
  deletePolicy: 'حذف وثيقة',
  AreYouSureDeletePolicy: 'هل أنت متأكد من رغبتك في حذف هذه الوثيقة من القائمة؟',
  vehicles: 'المركبات',
  drivers: 'السائقين',
  viewExistingPolicy: 'عرض وثيقة تأمين',
  purchaseInsurancePolicyTitle: 'شراء وثيقة تأمين جديدة',
  addNewVehicle: 'إضافة مركبة',
  addNewDriver: 'إضافة سائق',
  vehicleDetails: 'بيانات المركبة',
  driverDetails: 'بيانات السائق',
  vehicleNationality: 'جنسية المركبة',
  bahrain: 'البحرين',
  vehicleNumber: 'رقم المركبة',
  ownerIdNumber: 'رقم الهوية للمالك',
  ownerPersonalNumber: 'الرقم الشخصي للمالك',
  EnterOwnerIdNumber: 'أدخل رقم الهوية للمالك',
  ownerBlockNumber: 'رقم المجمع السكني للمالك',
  classOfUse: 'الفئة',
  ownerName: 'اسم المالك بالكامل',
  ownerName2: 'اسم المالك',
  EnterOwnerName: 'أدخل اسم المالك بالكامل',
  leavingMake: 'الصنع',
  leavingModel: 'الموديل',
  enteringMakeModel: 'الصنع/الموديل',
  SelectEnteringMakeModel: 'اختر الصنع/الموديل',
  vehicleType: 'نوع المركبة',
  color: 'اللون',
  SelectColor: 'اختر اللون',
  saveVehicleDetails: 'حفظ بيانات المركبة',
  duplicateVehicle: 'هذه المركبة موجودة مسبقاً',
  editEkeyVehicle: 'لا يمكن تعديل مركبات المفتاح الالكترون',
  driverIdNumber: 'رقم الهوية',
  EnterDriverIdNumber: 'أدخل رقم الهوية',
  driver: 'السائق',
  driverName: 'اسم السائق',
  driverFullName: 'الاسم بالكامل',
  EnterDriverFullName: 'أدخل الاسم بالكامل',
  driverNationality: 'الجنسية',
  driverMobileNumber: 'رقم الهاتف النقال',
  EnterDriverMobileNumber: 'أدخل رقم الهاتف النقال',
  driverEmail: 'البريد الإلكتروني',
  EnterDriverEmail: 'أدخل البريد الإلكتروني',
  driverConfirmEmail: 'تأكيد البريد الإلكتروني',
  EnterDriverConfirmEmail: 'أدخل تأكيد البريد الإلكتروني',
  driverConfirmEmailMismatch: 'عذراً، البريد الإلكتروني لا يتطابق، الرجاء التأكد من إدخال بياناتك الصحيحة',
  duplicateDriver: 'هذا السائق موجود مسبقاً',
  saveDriverDetails: 'حفظ بيانات السائق',
  deleteVehicle: 'حذف المركبة',
  AreYouSureDeleteVehicle: 'هل أنت متأكد من رغبتك في حذف هذه المركبة من القائمة؟',
  deleteDriver: 'حذف السائق',
  AreYouSureDeleteDriver: 'هل أنت متأكد من رغبتك في حذف هذا السائق من القائمة؟',
  selectVehicle: 'اختر رقم المركبة',
  selectDriver: 'اختر اسم السائق',
  selectDuration: 'اختر مدة التأمين',
  insuranceEndDateTime: 'وقت وتاريخ انتهاء التأمين',
  roadAssistance: 'الخدمة على الطريق',
  totalAmountDue: 'المبلغ الكلي المستحق',
  ownerType: 'نوع المالك',
  engineNumber: 'رقم المحرك',
  EnterEngineNumber: 'أدخل رقم المحرك',
  vehicleNumberofSeats: 'عدد المقاعد في المركبة',
  insuranceDetails: 'بيانات التأمين',
  insuranceStartDateTime: 'وقت وتاريخ بدء التأمين',
  insuranceDuration: 'مدة التأمين',
  feesDetails: 'بيانات الرسوم (د.ب)',
  insurancePolicyAmount: 'رسوم وثيقة التأمين',
  roadAssistanceAmount: 'رسوم الخدمة على الطريق',
  vatAmount: 'ضريبة القيمة المضافة',
  totalAmount: 'رسوم الدفع',
  renew: 'تمديد/تجديد',
  new: 'جديد',
  extend: 'تمديد',
  acceptUICTerms: 'أوافق على أحكام وشروط الشركة المتحدة للتأمين.',
  termsAndConditions: 'الشروط والأحكام',
  agree: 'أنا أوافق',
  kfcRenewMessage: 'الرجاء ملاحظة أنه من خلال تمديد وثيقة التأمين السارية أو القادمة، يتم إصدار وثيقة تأمين جديدة تبدأ من تاريخ ووقت انتهاء وثيقة التأمين السارية أو القادمة مباشرةً.',
  importantNote: 'ملاحظة هامة',
  kfcLeavingMessage: 'يجب أن تكون وثيقة التأمين صالحة لمدة 12 ساعة على الأقل عند مغادرة الجسر.',
  kfcEnteringMessage: 'يجب أن تكون وثيقة التأمين صالحة لمدة 3 أيام على الأقل عند مغادرة الجسر.',
  kfcBahrainVehicle: 'هذه الوثيقة تغطي السعودية فقط.',
  kfcSaudiVehicle: 'هذه الوثيقة تغطي البحرين فقط.',

  //Discount Vehicle Registration Renewal Fees
  vehicleRegistrationRenewalDiscount: 'تخفيض رسوم تجديد تسجيل المركبة',
  quickServices: 'الخدمات السريعة',
  applyDiscountForVehicle: 'تطبيق التخفيض على هذه المركبة',
  declareDiscountMessage: 'أقر بأني أريد تطبيق التخفيض بنسبة 50% على المركبة المذكورة.*',
  vehicleRegistrationRenewalDiscountMessage: 'الرجاء الأخذ بعين الاعتبار بأن هذه الخدمة مقدمة لأصحاب المركبات البحرينيين البالغين من العمر 60 عاماً أو أكثر.',

  //Reserved Plates
  ReservedPlates: 'أرقام اللوحات',
  plateNumber: 'رقم اللوحة',
  plateType: 'نوع اللوحة',
  plateExpiryDate: 'تاريخ الانتهاء',
  reservedPlatesReceipt: 'تفاصيل الدفع لأرقام اللوحات',

  //Webservice error
  errormsg: 'نعتذر لأي إزعاج، النظام لا يعمل حالياً. الرجاء المحاولة لاحقاً',
  sessionerror: 'انتهت الفترة الزمنية المحددة للتصفح. للمتابعة، الرجاء تسجيل الدخول مرة أخرى',
  locationError: 'الرجاء تفعيل خدمات الموقع لهذا التطبيق',
  bugText3: 'ليس لديك اتصال نشط بالإنترنت. الرجاء تفعيل الإنترنت ثم المحاولة مرة أخرى',

  appratetitle: 'قيم تطبيق خدمات المرور',
  appratemessage: 'ساهم في تطوير خدماتنا وتفضل بتقييم التطبيق',
  appratecancelbuttonlabel: 'لا، شكراً',
  appratelaterbuttonlabel: 'ذكرني لاحقاً',
  apprateratebuttonlabel: 'قيم البرنامج الآن',

  //ReportContraventions
  ReportContraventions: 'التبليغ عن المخالفات المرورية',
  VehicleColor: 'لون المركبة',
  SelectVehicleColor: 'اختر لون المركبة',
  PlateColor: 'لون اللوحة',
  SelectPlateColor: 'اختر لون اللوحة',
  PlateCountry: 'بلد اللوحة',
  SelectPlateCountry: 'اختر بلد اللوحة',
  PlateNumber: 'رقم اللوحة',
  EnterPlateCountry: 'أدخل رقم اللوحة',
  ContraventionItem: 'نوع المخالفة',
  SelectContraventionItem: 'اختر نوع المخالفة',
  SelectGovernorate: 'اختر المحافظة',
  SelectArea: 'اختر المنطقة',
  Location: 'الموقع',
  LocationDesc: 'وصف الموقع',
  EnterLocation: 'أدخل الموقع',
  EnterLocationDesc: 'إرشادات إضافية للموقع',
  Remark: 'ملاحظات',
  EnterRemark: 'أدخل الملاحظات',
  TakePhoto: 'إلتقط الصورة',
  PhotoSizeError: 'يجب أن لا يتجاوز حجم المرفق 2MB.',
  PhotoFormatError: 'نوع الملف المرفق غير صحيح',
  MinimumPhotos: 'الرجاء التقاط صورتين للمركبة.',
  ContraventionPhotos: 'صور المخالفة',
  Photo: 'صورة',
  CurrentLocation: 'الموقع الحالي',
  AgreeDeclaration: 'موافق',
  Declaration: 'أقر بأن جميع البيانات المدخلة صحيحة، وإني أتحمل كافة المسؤوليات القانونية المترتبة على خلاف ذلك. كما أكد حضوري في حال تم الاتصال بي من قبل النيابة العامة في حال اعتراض السائق على المخالفة.',
  MoreDetails: 'معلومات إضافية (اختياري)',
  LessDetails: 'معلومات إضافية (اختياري)',

  PaymentID: 'رقم السداد',
  reportingText1: 'يمكن الإبلاغ عن مخالفات الوقوف الخاطئ.',
  reportingText2: 'يجب التقاط صور حديثة للمخالفة المرتكبة تُظهر رقم المركبة وعدم تحميل صور سابقة',
  reportingText3: 'لا يمكن التقاط الصورة أثناء وجود المخالف داخل مركبته.',
  reportingText4: 'لا يمكن استخدام التطبيق أثناء التواجد في مقعد السائق.',

  Address: 'العنوان',
  WorkingHours: 'أوقات العمل',
  ContactDetails: 'بيانات الاتصال',

  //Traffic Accidents Services
  TrafficAccidentsServices: 'خدمات الحوادث المرورية',
  ComingSoon: 'قريباً',
  reportTrafficAccident: 'التبليغ عن الحوادث المرورية',
  trafficAccidentAcknowledgment: 'الإقرار بالتسبب بالحادث المروري',
  viewAccidentReport: 'عرض بلاغات الحوادث المرورية',
  viewInsuranceCompanies: 'مواقع شركات التأمين',
  callAccidentReport: 'اتصل على 199',
  AccidentDriverTittle: 'الرجاء تحديد السائق الذي سيقوم بالتبيلغ عن الحادث المروري:',
  affectedByTheAccident: 'السائق المتضرر من الحادث المروري',
  causedTheAccident: 'السائق المتسبب بالحادث المروري',
  TA_Q1_TEXT: 'يُسمح بالتبليغ عن الحوادث المرورية فقط عندما تكون جميع الأطراف متصالحة ولا توجد أية إصابات.',
  TA_Q2_TEXT: 'هل توجد إصابات ناتجة من الحادث المروري؟',
  individual: 'السائق',
  property: 'الممتلك',
  PropertyType: 'نوع الممتلك',
  PropertyOwnerName: 'اسم المالك',
  PropertyOwnerShipType: 'نوع الملكية',
  PropertyAddress: 'عنوان الممتلك',
  AccidentDetails: 'بيانات الحادث المروري',
  AccidentAddress: 'عنوان الحادث',
  AccidentLocation: 'موقع الحادث',
  TrafficAccidentLocation: 'موقع الحادث المروري',
  AccidentLocationCoordinates: 'إحداثيات موقع الحادث',
  AccidentDate: 'تاريخ الحادث',
  AccidentTime: 'وقت الحادث',
  AccidentPhotos: 'صور الحادث',
  AccidentDetails: 'بيانات الحادث المروري',
  AccidentSubmitNote: 'أقر بصحة المعلومات المدخلة، وأتحمل كامل المسؤولية القانونية المتعلقة بهذا الإجراء. *',
  AccidentSubmitNoteReporter: 'أقر بخطأ التسبب بالحادث المروري بين المركبة التي كنت أقودها (حسب البيانات المسجلة في البلاغ) والمركبات / الممتلكات الأخرى. كما أنني أخول شركات التأمين بتنفيذ بنود عقد التأمين وأؤكد على صحة ودقة البيانات المقدمة. إضافة الى ذلك، لا مانع لدي من حصول شركات التأمين على معلوماتي المسجلة لدى الإدارة العامة للمرور لغرض إصدار تقرير الحادث المروري. *',
  ReporterDetails: 'بيانات المُبلغ عن الحادث المروري',
  DriverCaused: 'السائق المتسبب بالحادث المروري',
  IdentityType: 'نوع الهوية',
  SelectNationality: 'اختر الجنسية',
  DriverIdIssueDate: 'تاريخ إصدار الهوية',
  DriverDetails: 'بيانات السائق',
  VehicleDetails: 'بيانات المركبة',
  SelectInsurance: 'اختر اسم شركة التأمين',
  InsurancePolicyNumber: 'رقم بوليصة التأمين',
  InsuranceCompanyDetails: 'بيانات شركة التأمين',
  Name: 'الاسم',
  BranchDetails: 'بيانات الفرع',
  IndividualsTitle: 'السائقين المتضررين من الحادث المروري',
  PropertyTitle: 'الممتلكات المتضررة من الحادث المروري',
  PropertyType: 'نوع الممتلك',
  PropertyName: 'اسم الممتلك',
  SelectPropertyType: 'اختر نوع الممتلك',
  SelectPropertyOwner: 'اختر اسم المالك',
  SelectPropertyOwnerShipType: 'اختر نوع الملكية',
  DeleteVehicle: 'حذف الممتلك',
  AreYouSureDeleteProperty: 'هل أنت متأكد من رغبتك في حذف الممتلك؟',
  ReportNumber: 'رقم البلاغ',
  EnterReportNumber: 'أدخل رقم البلاغ',
  LoginbyeKeyAccount: 'تسجيل الدخول بالمفتاح الإلكتروني',
  Owner: 'مالك المركبة',
  Driver: 'السائق',
  InvolvedVehicle: 'بيانات المركبة',
  InvolvedProperty: 'بيانات الممتلك',
  ReportDetails: 'بيانات البلاغ',
  ReportSubmitNote: 'أقر بخطأ التسبب بالحادث المروري بين المركبة التي كنت أقودها (حسب البيانات المسجلة في البلاغ) والمركبات/الممتلكات الأخرى. كما أنني أخول شركات التأمين بتنفيذ بنود عقد التأمين وأؤكد على صحة ودقة البيانات المقدمة. إضافة الى ذلك، لا مانع لدي من حصول شركات التأمين على معلوماتي المسجلة لدى الإدارة العامة للمرور لغرض إصدار تقرير الحادث المروري. *',
  Gender: 'الجنس',
  SelectGenderType: 'اختر الجنس',
  Male: 'ذكر',
  Female: 'أنثى',
  ResponsibleType: 'النوع',
  CausedTheTrafficAccident: 'المتسبب بالحادث المروري',
  AffectedByTheTrafficAccident: 'المتضرر من الحادث المروري',
  ReporterUserDetail: '* سيتم اعتبار هذا السائق هو المُبلغ عن الحادث المروري.',
  AffectedVehicleRequired: 'الرجاء إضافة سائق واحد على الأقل متضرر من الحادث المروري.',
  eKeyReporterRequired: 'الرجاء إضافة المستخدم المسجل دخوله بالمفتاح الإلكتروني إلى قائمة السائقين المتضررين من الحادث المروري.',
  EnterValidMobileNumber: 'الرجاء إدخال رقم الهاتف النقال الصحيح',
  VehicleAuthorization: 'تخويل المركبة لجسر الملك فهد',
  IssuanceVehicleAuthorization: 'إصدار تخويل مركبة',
  ManageVehicleAuthorizations: 'إدارة تخويلات المركبات الصادرة',
  AuthorizationValidityVerification: 'التحقق من صلاحية التخويل',
  DriverIdentityType: 'نوع هوية السائق',
  SelectDriverIdentityType: 'اختر نوع هوية السائق',
  DriverIdentityNumber: 'رقم هوية السائق',
  AuthorizationStartDate: 'تاريخ بدء التخويل',
  AuthorizationEndDate: 'تاريخ انتهاء التخويل',
  AuthorizationMaxStartDate: 'يجب ألا يتجاوز تاريخ بدء التخويل ',
  AuthorizationMaxDate: 'يجب ألا يتجاوز تاريخ انتهاء التخويل  ',
  AuthorizationEndDateError: 'يجب ألا يكون تاريخ انتهاء التخويل قبل تاريخ بدء التخويل.',
  CountriesIncludedAuthorization: 'الدول المدرجة في التخويل',
  OwnerMobileNumber: 'رقم الهاتف النقال للمالك',
  OwnerEmail: 'البريد الإلكتروني للمالك',
  DriverMobileNumber: 'رقم الهاتف النقال للسائق',
  DriverEmail: 'البريد الإلكتروني للسائق',
  AuthorizationDetails: 'بيانات التخويل',
  Declare: 'أقر بصحة المعلومات المدخلة، وأتحمل كامل المسؤولية القانونية المتعلقة بهذا الإجراء. *',
  AuthorizationCertificate: 'شهادة التخويل',
  AuthorizationNumber: 'رقم التخويل',
  Authorization: 'التخويل',
  EnterAuthorizationNumber: 'أدخل رقم التخويل',
  StartDate: 'تاريخ البدء',
  EndDate: 'تاريخ الانتهاء',
  ViewCertificate: 'عرض الشهادة',
  IssuedAuthorizationCertificateDetails: 'بيانات التخويلات الصادرة',
  VehicleAuthorizationCertificateDetails: 'بيانات شهادة تخويل المركبة',
  AuthorizationCertificateNote: 'الرجاء طباعة شهادة التخويل للاستخدام عند الضرورة. في حال سيتم استخدام التخويل خارج دول الخليج، الرجاء زيارة الإدارة العامة للمرور لختم الشهادة.',
  CancelAuthorization: 'هل أنت متأكد من رغبتك في إلغاء التخويل؟',
  Or: '-- أو --',
  ScanQr: 'مسح',
  QRError: 'الرمز غير صحيح'
};

angular.module('gdtApp.languageFactory', []) /*Language factory */
  .factory('language', ['$rootScope', 'cssInjector', function($rootScope, cssInjector) {

    const language = {};
    language.getName = function() {

      if ($rootScope.language == 'English') {
        $rootScope.languageArr = $rootScope.english;
        $rootScope.applanguage = 'English';
        cssInjector.removeAll();
        //return english;
      } else {
        cssInjector.add('css/arabic.css');

        $rootScope.languageArr = $rootScope.arabic;
        $rootScope.applanguage = 'Arabic';

        //return arabic;
      }
      localStorage.applanguage = $rootScope.applanguage;
      console.log('settingLanguage: ' + $rootScope.applanguage);
    };
    return language;

  }]);
